# COVID Analysis - Sorting Countries

## Import libraries

In [1]:
import pandas as pd
import numpy as np

## Loading dataset

In [2]:
df = pd.read_csv('country_vaccination_preprocessed.csv')
df.head()

,country,iso_code,date,total_vaccinations,people_vaccinated,people_fully_vaccinated,daily_vaccinations_raw,daily_vaccinations,total_vaccinations_per_hundred,people_vaccinated_per_hundred,people_fully_vaccinated_per_hundred,daily_vaccinations_per_million,vaccines,source_name,source_website,year,month,day,month_name
0,Afghanistan,AFG,2021-05-27,593313.0,479574.0,113739.0,2859.0,6487.0,1.49,1.20,0.29,163.0,"Johnson&Johnson, Oxford/AstraZeneca, Pfizer/Bi...",World Health Organization,https://covid19.who.int/,2021,5,27,May
1,Afghanistan,AFG,2021-06-03,630305.0,481800.0,148505.0,4015.0,5285.0,1.58,1.21,0.37,133.0,"Johnson&Johnson, Oxford/AstraZeneca, Pfizer/Bi...",World Health Organization,https://covid19.who.int/,2021,6,3,Jun
2,Afghanistan,AFG,2022-01-27,5081064.0,4517380.0,3868832.0,6868.0,9802.0,12.76,11.34,9.71,246.0,"Johnson&Johnson, Oxford/AstraZeneca, Pfizer/Bi...",World Health Organization,https://covid19.who.int/,2022,1,27,Jan
3,Albania,ALB,2021-02-18,3049.0,2438.0,611.0,1348.0,254.0,0.11,0.08,0.02,88.0,"Oxford/AstraZeneca, Pfizer/BioNTech, Sinovac, ...",Ministry of Health,https://shendetesia.gov.al/vaksinimi-anticovid...,2021,2,18,Feb
4,Albania,ALB,2021-05-11,622507.0,440921.0,181586.0,9548.0,12160.0,21.67,15.35,6.32,4233.0,"Oxford/AstraZeneca, Pfizer/BioNTech, Sinovac, ...",Ministry of Health,https://shendetesia.gov.al/vaksinimi-anticovid...,2021,5,11,May

In [3]:
# getting sum of total vaccinations group by country
data = df.groupby('country').sum()['total_vaccinations']

In [4]:
# dataframe presentation of output
def dataframe(df):
    df_ = pd.DataFrame()
    df_['country'] = df.index
    df_['total_vaccinations'] = df.values
    return df_

##  1.Which Country is having least total Vaccinations?

In [5]:
nw_data = data.sort_values().head()
dataframe(nw_data)

            country  total_vaccinations
0           Burundi              6340.0
1           Andorra             15269.0
2  French Polynesia             16252.0
3           Grenada             24336.0
4             Gabon             33591.0

## 2.Which Country is having the most total Vaccinations?

In [6]:
nw_data = data.sort_values( ascending = False).head()
dataframe(nw_data)

         country  total_vaccinations
0          India        3.200418e+11
1  United States        1.550138e+11
2         Brazil        7.637582e+10
3          China        4.858702e+10
4      Indonesia        4.272175e+10